#!/bin/sh
KEY="$HOME/.ssh/id_rsa.pub"
if [ ! -f $KEY ];then
echo "private key not found at $KEY"
      echo "* please create it with "ssh-keygen -t rsa" *"
      echo "* to login to the remote host without a password don't give the key you create with ssh-keygen a password! *"
      exit
fi

if [ -z $1 ];then
echo "Please specify user@host.tld as the first switch to this script"
      exit
fi

echo "Putting your environment on $1... "

cd ~ && tar czvf vimstuff.tgz .vim/
scp ~/vimstuff.tgz $1:~/
echo "Untaring vimstuff..."
ssh -q $1 "bash -c 'mkdir -p ~/.backup; cd; tar zxf vimstuff.tgz'"

cd ~ && tar czvf dotfiles.tgz .dot_files/
scp ~/dotfiles.tgz $1:~/
echo "Untaring dot_files..."
ssh -q $1 "bash -c 'mkdir -p ~/.backup; cd; tar zxf dot_files.tgz'"

# TODO: run setup scripts for dot_files

echo "done!"
